theme: jekyll-theme-minimal
url: https://thabanibiyela.github.io/platform-accounting-public/

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

nav_links:
  - title: Overview
    url: /
  - title: Data Model
    url: /data-model
  - title: Workflows
    url: /workflows
  - title: CLI
    url: /cli
  - title: BI
    url: /bi
  - title: Report
    url: /report

logo: assets/images/profile1_small.png
title: Thabani Biyela, ACA
description: Part of the collection of my work in finance automation showcasing how I use Python, SQL, JavaScript, and GCP to solve complex financial problems and build data-driven tools.
